package com.sipanduberadat.user.adapters

import android.content.Context
import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.recyclerview.widget.RecyclerView
import com.sipanduberadat.user.R
import com.sipanduberadat.user.models.*
import com.sipanduberadat.user.viewHolders.ReportHistoryViewHolder
import java.util.*

class ReportHistoryRecyclerAdapter(
        private val context: Context
): RecyclerView.Adapter<ReportHistoryViewHolder>() {

    private val items: List<Pelaporan> = listOf(
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
            JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Kembang Kencana", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", true),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi"),
            Pelaporan(1,
                    Krama(1,
                            Banjar(1,
                                    DesaAdat(1,
                                            Kecamatan(1,
                                                    Kabupaten(1,
                                                            Provinsi(1,
                                                                    Negara(1, "Indonesia",
                                                                            true), "Bali",
                                                                    true), "Badung",
                                                            true), "Abiansemal",
                                                    true), "ABC", 0.0,
                                            0.0, true), "AAA",
                                    true), "Made ABC", "test.png",
                            "000", Calendar.getInstance().time, "123", "Laki-laki",
                            "Krama Wid", validStatus = true, activeStatus = true),
                    DesaAdat(1,
                            Kecamatan(1,
                                    Kabupaten(1,
                                            Provinsi(1,
                                                    Negara(1, "Indonesia",
                                                            true), "Bali",
                                                    true), "Badung",
                                            true), "Abiansemal",
                                    true), "Abian Naga", 0.0,
                            0.0, true),
                    JenisPelaporan(1, "Hujan Badai", "test.png", false),
                    Calendar.getInstance().time, 0.0, 0.0, "Menunggu Validasi")
    )

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ReportHistoryViewHolder {
        val view = LayoutInflater.from(context).inflate(R.layout.layout_card_report_history, parent,
                false)
        return ReportHistoryViewHolder(view)
    }

    override fun getItemCount(): Int {
        return items.size
    }

    override fun onBindViewHolder(holder: ReportHistoryViewHolder, position: Int) {
        holder.bindItem(items[position])
    }

}